// This file is automatically generated. Do not edit it directly.
// (Manual exception: the hardcoded fallbacks below are required because
// Lovable's build environment doesn't expose VITE_ env vars after we
// stopped tracking .env in the repo. The values are publishable by
// Supabase design — same safety as the Sentry DSN fallback in main.tsx.)
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL_FALLBACK = "https://rbsghoxhcpvrnkemksex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY_FALLBACK = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJic2dob3hoY3B2cm5rZW1rc2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNzQwNDcsImV4cCI6MjA4MzY1MDA0N30.qxQ7-JxInZs5-RKicxOwmFVhWM4qmAuGlLv-QBUctQI";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || SUPABASE_URL_FALLBACK;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY_FALLBACK;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
